/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulatorrangkaianlistrik;

//import Controller.TampilanController;
import Komponen.Resistor.GambarResistor;
import Komponen.Hitung;
import Komponen.Oscilloscope;
import Komponen.Plot;
//import Komponen.Resistor;
/**
 *
 * @author Agung DP
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Rangkaian
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        field1 = new javax.swing.JLabel();
        field2 = new javax.swing.JLabel();
        rangkaianseri = new javax.swing.JLabel();
        rangkaianrc = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        field1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(field1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 130, 20));

        field2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(field2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 120, 20));

        rangkaianseri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/rangkaian-seri.png"))); // NOI18N
        rangkaianseri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rangkaianseriMouseClicked(evt);
            }
        });
        getContentPane().add(rangkaianseri, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        rangkaianrc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/rangkaian-rc.png"))); // NOI18N
        rangkaianrc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rangkaianrcMouseClicked(evt);
            }
        });
        getContentPane().add(rangkaianrc, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/bg.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rangkaianseriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rangkaianseriMouseClicked
        // TODO add your handling code here:
        //Plot.setStatus(1);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RangkaianSeri().setVisible(true);
            }
        });
    }//GEN-LAST:event_rangkaianseriMouseClicked

    private void rangkaianrcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rangkaianrcMouseClicked
        // TODO add your handling code here:
        //Plot.setStatus(2);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RangkaianRC().setVisible(true);
            }
        });
    }//GEN-LAST:event_rangkaianrcMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Rangkaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Rangkaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Rangkaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Rangkaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Rangkaian().setVisible(true);
//            }
//        });
//    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel field1;
    private javax.swing.JLabel field2;
    private javax.swing.JLabel rangkaianrc;
    private javax.swing.JLabel rangkaianseri;
    // End of variables declaration//GEN-END:variables
}
