/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulatorrangkaianlistrik;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Agung DP
 */
public class RangkaianSeri extends javax.swing.JFrame {

    /**
     * Creates new form RangkaianSeri
     */
    private final int nIpb = 10;
    int teks = 0;
    int r = teks;
    private Timer timer;
    public RangkaianSeri() {
        initComponents();
        this.setLocationRelativeTo(null);
        ipb.setEnabled(true);
        start();
    }
    
    private void start(){
        int speed = 1000;
        ActionListener action = new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                lbl.setText(String.valueOf(r));
                r++;
            }
        };
        timer = new Timer(speed, action);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ipb = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ipb.setBackground(new java.awt.Color(0, 0, 0));
        ipb.setFont(new java.awt.Font("DialogInput", 0, 60)); // NOI18N
        ipb.setForeground(new java.awt.Color(255, 255, 0));
        ipb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/ipb.png"))); // NOI18N
        ipb.setOpaque(true);
        getContentPane().add(ipb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 640, -1));

        lbl.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        getContentPane().add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, 227, 201));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RangkaianSeri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RangkaianSeri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RangkaianSeri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RangkaianSeri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RangkaianSeri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ipb;
    private javax.swing.JLabel lbl;
    // End of variables declaration//GEN-END:variables
}
