/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Komponen.Resistor;

import Komponen.Hitung;
import Komponen.Plot;
import Komponen.PlotDasar;
import simulatorrangkaianlistrik.Home;
import simulatorrangkaianlistrik.RangkaianRC;
/**
 *
 * @author Agung DP
 */
public class GambarResistor extends javax.swing.JFrame {

    /**
     * Creates new form GambarResistor
     */
    
    public GambarResistor() {
        initComponents();
        InitCincin.setCincin();
        this.getRootPane().setDefaultButton(Ok);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cincin1 = new javax.swing.JComboBox<>();
        cincin2 = new javax.swing.JComboBox<>();
        cincin3 = new javax.swing.JComboBox<>();
        cincin4 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cincinputih3 = new javax.swing.JLabel();
        cincinputih2 = new javax.swing.JLabel();
        cincinputih1 = new javax.swing.JLabel();
        cincinabuabu3 = new javax.swing.JLabel();
        cincinabuabu2 = new javax.swing.JLabel();
        cincinabuabu1 = new javax.swing.JLabel();
        cincinungu1 = new javax.swing.JLabel();
        cincinbiru1 = new javax.swing.JLabel();
        cincinhijau1 = new javax.swing.JLabel();
        cincinkuning1 = new javax.swing.JLabel();
        cincinorange1 = new javax.swing.JLabel();
        cincinmerah1 = new javax.swing.JLabel();
        cincincokelat1 = new javax.swing.JLabel();
        cincinhitam1 = new javax.swing.JLabel();
        cincinungu2 = new javax.swing.JLabel();
        cincinbiru2 = new javax.swing.JLabel();
        cincinhijau2 = new javax.swing.JLabel();
        cincinkuning2 = new javax.swing.JLabel();
        cincinorange2 = new javax.swing.JLabel();
        cincinmerah2 = new javax.swing.JLabel();
        cincincokelat2 = new javax.swing.JLabel();
        cincinhitam2 = new javax.swing.JLabel();
        cincinungu3 = new javax.swing.JLabel();
        cincinbiru3 = new javax.swing.JLabel();
        cincinhijau3 = new javax.swing.JLabel();
        cincinkuning3 = new javax.swing.JLabel();
        cincinorange3 = new javax.swing.JLabel();
        cincinmerah3 = new javax.swing.JLabel();
        cincincokelat3 = new javax.swing.JLabel();
        cincinhitam3 = new javax.swing.JLabel();
        cincinperak4 = new javax.swing.JLabel();
        cincinemas4 = new javax.swing.JLabel();
        nomorcincin4 = new javax.swing.JLabel();
        nomorcincin3 = new javax.swing.JLabel();
        nomorcincin2 = new javax.swing.JLabel();
        nomorcincin1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        outputnilai = new javax.swing.JLabel();
        gambarresistor = new javax.swing.JLabel();
        hitung = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Ok = new javax.swing.JButton();
        manualarea = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cincin1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cincin1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hitam", "Cokelat", "Merah", "Orange", "Kuning", "Hijau", "Biru", "Ungu", "Abu-Abu", "Putih" }));
        cincin1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cincin1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(cincin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 140, 40));

        cincin2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cincin2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hitam", "Cokelat", "Merah", "Orange", "Kuning", "Hijau", "Biru", "Ungu", "Abu-Abu", "Putih" }));
        cincin2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cincin2PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(cincin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 140, 40));

        cincin3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cincin3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hitam", "Cokelat", "Merah", "Orange", "Kuning", "Hijau", "Biru", "Ungu", "Abu-Abu", "Putih" }));
        cincin3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cincin3PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(cincin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 140, 40));

        cincin4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cincin4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Emas", "Perak", "Tak Berwarna" }));
        cincin4.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cincin4PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(cincin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 140, 40));

        jLabel6.setFont(new java.awt.Font("Myriad Pro", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Nilai Resistor/Hambatan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 420, 60));

        cincinputih3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/putih.png"))); // NOI18N
        getContentPane().add(cincinputih3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, -1, -1));

        cincinputih2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/putih.png"))); // NOI18N
        getContentPane().add(cincinputih2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, -1, -1));

        cincinputih1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/putih.png"))); // NOI18N
        getContentPane().add(cincinputih1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, -1, -1));

        cincinabuabu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/abuabu.png"))); // NOI18N
        getContentPane().add(cincinabuabu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, -1, -1));

        cincinabuabu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/abuabu.png"))); // NOI18N
        getContentPane().add(cincinabuabu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, -1, -1));

        cincinabuabu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/abuabu.png"))); // NOI18N
        getContentPane().add(cincinabuabu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, -1, -1));

        cincinungu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/ungu.png"))); // NOI18N
        getContentPane().add(cincinungu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, -1, -1));

        cincinbiru1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/biru.png"))); // NOI18N
        getContentPane().add(cincinbiru1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, -1, -1));

        cincinhijau1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/hijau.png"))); // NOI18N
        getContentPane().add(cincinhijau1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, -1, -1));

        cincinkuning1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/kuning.png"))); // NOI18N
        getContentPane().add(cincinkuning1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, -1, -1));

        cincinorange1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/orange.png"))); // NOI18N
        getContentPane().add(cincinorange1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, -1, -1));

        cincinmerah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/merah.png"))); // NOI18N
        getContentPane().add(cincinmerah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, -1, -1));

        cincincokelat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/cokelat.png"))); // NOI18N
        getContentPane().add(cincincokelat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, -1, -1));

        cincinhitam1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/hitam.png"))); // NOI18N
        getContentPane().add(cincinhitam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, -1, -1));

        cincinungu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/ungu.png"))); // NOI18N
        getContentPane().add(cincinungu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, -1, -1));

        cincinbiru2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/biru.png"))); // NOI18N
        getContentPane().add(cincinbiru2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, -1, -1));

        cincinhijau2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/hijau.png"))); // NOI18N
        getContentPane().add(cincinhijau2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, -1, -1));

        cincinkuning2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/kuning.png"))); // NOI18N
        getContentPane().add(cincinkuning2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, -1, -1));

        cincinorange2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/orange.png"))); // NOI18N
        getContentPane().add(cincinorange2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, -1, -1));

        cincinmerah2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/merah.png"))); // NOI18N
        getContentPane().add(cincinmerah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, -1, -1));

        cincincokelat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/cokelat.png"))); // NOI18N
        getContentPane().add(cincincokelat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, -1, -1));

        cincinhitam2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/hitam.png"))); // NOI18N
        getContentPane().add(cincinhitam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, -1, -1));

        cincinungu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/ungu.png"))); // NOI18N
        getContentPane().add(cincinungu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, -1, -1));

        cincinbiru3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/biru.png"))); // NOI18N
        getContentPane().add(cincinbiru3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, -1, -1));

        cincinhijau3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/hijau.png"))); // NOI18N
        getContentPane().add(cincinhijau3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, -1, -1));

        cincinkuning3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/kuning.png"))); // NOI18N
        getContentPane().add(cincinkuning3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, -1, -1));

        cincinorange3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/orange.png"))); // NOI18N
        getContentPane().add(cincinorange3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, -1, -1));

        cincinmerah3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/merah.png"))); // NOI18N
        getContentPane().add(cincinmerah3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, -1, -1));

        cincincokelat3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/cokelat.png"))); // NOI18N
        getContentPane().add(cincincokelat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, -1, -1));

        cincinhitam3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/hitam.png"))); // NOI18N
        getContentPane().add(cincinhitam3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, -1, -1));

        cincinperak4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/perak.png"))); // NOI18N
        getContentPane().add(cincinperak4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, -1, -1));

        cincinemas4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cincin/emas.png"))); // NOI18N
        getContentPane().add(cincinemas4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, -1, -1));

        nomorcincin4.setText("4");
        getContentPane().add(nomorcincin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, -1, -1));

        nomorcincin3.setText("3");
        getContentPane().add(nomorcincin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, -1, -1));

        nomorcincin2.setText("2");
        getContentPane().add(nomorcincin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, -1, -1));

        nomorcincin1.setText("1");
        getContentPane().add(nomorcincin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Warna Cincin 4");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 150, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Warna Cincin 3");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 150, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Warna Cincin 2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 150, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Warna Cincin 1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 150, 40));

        outputnilai.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        outputnilai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(outputnilai, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 340, 50));

        gambarresistor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/resistor.png"))); // NOI18N
        getContentPane().add(gambarresistor, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, -1, 160));

        hitung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/NEXT_ICON.png"))); // NOI18N
        hitung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hitungMouseClicked(evt);
            }
        });
        getContentPane().add(hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/BACK_ICON.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Atau Langsung Input");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 310, 40));

        Ok.setText("Ok");
        Ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OkMouseClicked(evt);
            }
        });
        Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkActionPerformed(evt);
            }
        });
        getContentPane().add(Ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 429, -1, 40));

        manualarea.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(manualarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 170, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pilih Warna Cincin:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/bg_main.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cincin1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cincin1PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        int p = cincin1.getSelectedIndex();
        InitCincin.getCincin1(p);
    }//GEN-LAST:event_cincin1PopupMenuWillBecomeInvisible

    private void cincin2PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cincin2PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        int p = cincin2.getSelectedIndex();
        InitCincin.getCincin2(p);
    }//GEN-LAST:event_cincin2PopupMenuWillBecomeInvisible

    private void cincin3PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cincin3PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        int p = cincin3.getSelectedIndex();
        InitCincin.getCincin3(p);
    }//GEN-LAST:event_cincin3PopupMenuWillBecomeInvisible

    private void cincin4PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cincin4PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        int p = cincin4.getSelectedIndex();
        InitCincin.getCincin4(p);
    }//GEN-LAST:event_cincin4PopupMenuWillBecomeInvisible

    private void hitungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hitungMouseClicked
        // TODO add your handling code here:
        long nilaihambatan = NilaiResistor.getHambatanMinimum();
        if(nilaihambatan >= 1000){
            double resis =(double) nilaihambatan/1000;
            String hasil = Double.toString(resis);
            outputnilai.setText("Nilai = "+hasil+" KOhm");
        }
        else{
            String hasil = Long.toString(nilaihambatan);
            outputnilai.setText("Nilai = "+hasil+" Ohm");
        }
        //Hitung.setHambatan(nilaihambatan);
        Hitung.setHambatan(nilaihambatan);
        Plot.setHambatan(nilaihambatan);
        PlotDasar.setHambatan(nilaihambatan);
        RangkaianRC.labelresistor.setText(Long.toString(nilaihambatan)+ " Ohm");
        //setVisible(false);
    }//GEN-LAST:event_hitungMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_backMouseClicked

    private void OkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OkMouseClicked
        // TODO add your handling code here:
        String hasil2 = manualarea.getText();
        long nilaihambatanmanual =(long) Double.parseDouble(hasil2);
        if(nilaihambatanmanual >= 1000){
            double resis =(double) nilaihambatanmanual/1000;
            String hasil = Double.toString(resis);
            outputnilai.setText("Nilai = "+hasil+" KOhm");
        }
        else{
            String hasil = Long.toString(nilaihambatanmanual);
            outputnilai.setText("Nilai = "+hasil+" Ohm");
        }
        
        InitCincinOtomatis.setNilai(nilaihambatanmanual);
        InitCincinOtomatis.getCincinOtomatis();
        //method untuk main page
        long nilaihambatan2 = NilaiResistor.getHambatanMinimum();
        Hitung.setHambatan(nilaihambatan2);
        Plot.setHambatan(nilaihambatan2);
        PlotDasar.setHambatan(nilaihambatan2);
        RangkaianRC.labelresistor.setText(Long.toString(nilaihambatan2)+ " Ohm");
        //end
    }//GEN-LAST:event_OkMouseClicked

    private void OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkActionPerformed
        // TODO add your handling code here:
        String hasil2 = manualarea.getText();
        long nilaihambatanmanual =(long) Double.parseDouble(hasil2);
        if(nilaihambatanmanual >= 1000){
            double resis =(double) nilaihambatanmanual/1000;
            String hasil = Double.toString(resis);
            outputnilai.setText("Nilai = "+hasil+" KOhm");
        }
        else{
            String hasil = Long.toString(nilaihambatanmanual);
            outputnilai.setText("Nilai = "+hasil+" Ohm");
        }
        
        InitCincinOtomatis.setNilai(nilaihambatanmanual);
        InitCincinOtomatis.getCincinOtomatis();
        //method untuk main page
        long nilaihambatan2 = NilaiResistor.getHambatanMinimum();
        Hitung.setHambatan(nilaihambatan2);
        //setVisible(false);
        //end
    }//GEN-LAST:event_OkActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GambarResistor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GambarResistor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GambarResistor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GambarResistor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GambarResistor().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ok;
    private javax.swing.JLabel back;
    private javax.swing.JLabel background;
    private javax.swing.JComboBox<String> cincin1;
    private javax.swing.JComboBox<String> cincin2;
    private javax.swing.JComboBox<String> cincin3;
    private javax.swing.JComboBox<String> cincin4;
    protected static javax.swing.JLabel cincinabuabu1;
    protected static javax.swing.JLabel cincinabuabu2;
    protected static javax.swing.JLabel cincinabuabu3;
    protected static javax.swing.JLabel cincinbiru1;
    protected static javax.swing.JLabel cincinbiru2;
    protected static javax.swing.JLabel cincinbiru3;
    protected static javax.swing.JLabel cincincokelat1;
    protected static javax.swing.JLabel cincincokelat2;
    protected static javax.swing.JLabel cincincokelat3;
    protected static javax.swing.JLabel cincinemas4;
    protected static javax.swing.JLabel cincinhijau1;
    protected static javax.swing.JLabel cincinhijau2;
    protected static javax.swing.JLabel cincinhijau3;
    protected static javax.swing.JLabel cincinhitam1;
    protected static javax.swing.JLabel cincinhitam2;
    protected static javax.swing.JLabel cincinhitam3;
    protected static javax.swing.JLabel cincinkuning1;
    protected static javax.swing.JLabel cincinkuning2;
    protected static javax.swing.JLabel cincinkuning3;
    protected static javax.swing.JLabel cincinmerah1;
    protected static javax.swing.JLabel cincinmerah2;
    protected static javax.swing.JLabel cincinmerah3;
    protected static javax.swing.JLabel cincinorange1;
    protected static javax.swing.JLabel cincinorange2;
    protected static javax.swing.JLabel cincinorange3;
    protected static javax.swing.JLabel cincinperak4;
    protected static javax.swing.JLabel cincinputih1;
    protected static javax.swing.JLabel cincinputih2;
    protected static javax.swing.JLabel cincinputih3;
    protected static javax.swing.JLabel cincinungu1;
    protected static javax.swing.JLabel cincinungu2;
    protected static javax.swing.JLabel cincinungu3;
    private javax.swing.JLabel gambarresistor;
    private javax.swing.JLabel hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField manualarea;
    private static javax.swing.JLabel nomorcincin1;
    private static javax.swing.JLabel nomorcincin2;
    private static javax.swing.JLabel nomorcincin3;
    private static javax.swing.JLabel nomorcincin4;
    private javax.swing.JLabel outputnilai;
    // End of variables declaration//GEN-END:variables
}
